/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerPelatihan;
import Processor.FeatureExtractor.Zoning.Zoning;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author acdwisu
 */
public class MenuKonfigEkstraksiFitur extends javax.swing.JFrame {

    public static final int TIPE_AZ = 1;
    public static final int TIPE_SZ = 2;
    
    private int tipe;
    
    private ControllerPelatihan controller;
    
    /**
     * Creates new form MenuKonfigEkstraksiFitur
     */
    public MenuKonfigEkstraksiFitur(ControllerPelatihan controller, int tipe, HashMap<String,Integer> config) {                
        this.controller = controller;
        this.tipe = tipe;
        
        initComponents();
        
        this.spinnerRentangX.setValue(config.get("offsetX"));
        this.spinnerRentangY.setValue(config.get("offsetY"));
        this.spinnerZonaHorizontal.setValue(config.get("zoneHorizontalCount"));
        this.spinnerZonaVertikal.setValue(config.get("zoneVerticalCount"));
        
        switch(this.tipe) {
            case TIPE_AZ : 
                
                break;
            case TIPE_SZ :
                this.spinnerRentangX.setEnabled(false);
                this.spinnerRentangY.setEnabled(false);
                this.labelRentangX.setEnabled(false);
                this.labelRentangY.setEnabled(false);
                break;
        }
        
        /* Set Look and Feel Swing */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MenuKonfigEkstraksiFitur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelRentangX = new javax.swing.JLabel();
        labelRentangY = new javax.swing.JLabel();
        spinnerZonaVertikal = new javax.swing.JSpinner();
        spinnerZonaHorizontal = new javax.swing.JSpinner();
        spinnerRentangX = new javax.swing.JSpinner();
        spinnerRentangY = new javax.swing.JSpinner();
        buttonSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Konfigurasi Ekstraksi Fitur");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Jumlah Zona Vertikal :");

        jLabel2.setText("Jumlah Zona Horizontal :");

        labelRentangX.setText("Rentang Pencarian X :");

        labelRentangY.setText("Rentang Pencarian Y :");

        spinnerZonaVertikal.setModel(new javax.swing.SpinnerNumberModel(3, 1, null, 1));

        spinnerZonaHorizontal.setModel(new javax.swing.SpinnerNumberModel(3, 1, null, 1));

        spinnerRentangX.setModel(new javax.swing.SpinnerNumberModel(3, null, 10, 1));

        spinnerRentangY.setModel(new javax.swing.SpinnerNumberModel(3, null, 10, 1));

        buttonSimpan.setText("Simpan");
        buttonSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSimpanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(labelRentangX)
                            .addComponent(labelRentangY))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinnerZonaVertikal, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(spinnerZonaHorizontal)
                            .addComponent(spinnerRentangX)
                            .addComponent(spinnerRentangY)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(buttonSimpan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spinnerZonaVertikal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinnerZonaHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRentangX)
                    .addComponent(spinnerRentangX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRentangY)
                    .addComponent(spinnerRentangY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSimpanMouseClicked
        this.controller.setExtractionConfig(this.retrieveConfigs());
        
        JOptionPane.showMessageDialog(this, "Konfigurasi telah tersimpan");
    }//GEN-LAST:event_buttonSimpanMouseClicked

    private HashMap<String, Integer> retrieveConfigs() {
        HashMap<String, Integer> config = new HashMap<>();
        
        config.put("zoneVerticalCount", (Integer) this.spinnerZonaVertikal.getValue());
        config.put("zoneHorizontalCount", (Integer) this.spinnerZonaHorizontal.getValue());
        
        int zoneType = 0;
        if(this.tipe == TIPE_AZ) zoneType = Zoning.ADAPTIVE_ZONE;
        else if(this.tipe == TIPE_SZ) zoneType = Zoning.STATIC_ZONE;
        
        config.put("zoneType", zoneType);
        
        if(this.tipe == TIPE_AZ) {
            config.put("offsetX", (Integer) this.spinnerRentangX.getValue());
            config.put("offsetY", (Integer) this.spinnerRentangY.getValue());
        } else {
            config.put("offsetX", 0);
            config.put("offsetY", 0);
        }
        
        return config;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelRentangX;
    private javax.swing.JLabel labelRentangY;
    private javax.swing.JSpinner spinnerRentangX;
    private javax.swing.JSpinner spinnerRentangY;
    private javax.swing.JSpinner spinnerZonaHorizontal;
    private javax.swing.JSpinner spinnerZonaVertikal;
    // End of variables declaration//GEN-END:variables
}
