/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerPelatihan;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author acdwisu
 */
public class MenuPelatihan extends javax.swing.JFrame {

    private ControllerPelatihan controller;
    
    /**
     * Creates new form MenuPelatihan
     */
    public MenuPelatihan() {
        initComponents();
        
        /* Set Look and Feel Swing */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MenuPelatihan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        controller = new ControllerPelatihan(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNamaPelatihan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboMetodeEkstraksi = new javax.swing.JComboBox<>();
        comboDataset = new javax.swing.JComboBox<>();
        spinnerJumlahTree = new javax.swing.JSpinner();
        buttonEditParameter = new javax.swing.JButton();
        comboCountAttributesCheckType = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        buttonMulaiPelatihan = new javax.swing.JButton();
        progressPelatihan = new javax.swing.JProgressBar();
        labelInfoProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pelatihan");
        setResizable(false);

        jLabel1.setText("Simpan sebagai : ");

        textNamaPelatihan.setToolTipText("Nama hasil pelatihan");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Konfigurasi"));

        jLabel2.setText("Metode Ekstraksi Fitur :");

        jLabel3.setText("Dataset :");

        jLabel4.setText("Jumlah Tree RF :");

        comboMetodeEkstraksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SZLS -Static Zoning Line Segments-based-", "AZLS -Adaptive Zoning Line Segments-based-", "SZPD -Static Zoning Pixel Density-based-", "AZPD -Adaptive Zoning Pixel Density-based-", "SZZC -Static Zoning Zone Characteristics-based-", "AZZC -Adaptive Zoning Zone Characteristics-based-", "WUMI -Weighted United Moment Invariants-" }));
        comboMetodeEkstraksi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboMetodeEkstraksiItemStateChanged(evt);
            }
        });

        spinnerJumlahTree.setModel(new javax.swing.SpinnerNumberModel(500, 1, null, 1));

        buttonEditParameter.setText("Edit Parameter");
        buttonEditParameter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEditParameterMouseClicked(evt);
            }
        });

        comboCountAttributesCheckType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "log(M) / log(2) + 1", "sqrt(M)" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboMetodeEkstraksi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboDataset, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonEditParameter))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spinnerJumlahTree, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboCountAttributesCheckType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboMetodeEkstraksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEditParameter))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDataset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinnerJumlahTree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCountAttributesCheckType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonMulaiPelatihan.setText("Mulai Pelatihan");
        buttonMulaiPelatihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMulaiPelatihanMouseClicked(evt);
            }
        });

        labelInfoProgress.setText("Selesai : ");
        labelInfoProgress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressPelatihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelInfoProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(buttonMulaiPelatihan)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonMulaiPelatihan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(progressPelatihan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInfoProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNamaPelatihan))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNamaPelatihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditParameterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditParameterMouseClicked
        int type = -1;
        
        int[] tipeSZ = {0,2,4};
        int[] tipeAZ = {1,3,5};
        
        int selectedIndex = this.comboMetodeEkstraksi.getSelectedIndex();
        
        for(int sz : tipeSZ) {
            if(sz == selectedIndex) {
                type = MenuKonfigEkstraksiFitur.TIPE_SZ;
                break;
            }
        }
        
        if(type == -1) {
            for(int az : tipeAZ) {
                if(az == selectedIndex) {
                    type = MenuKonfigEkstraksiFitur.TIPE_AZ;
                }
            }
        }
        
        if(type != -1) {
            this.controller.responseEditParameterEkstraksi(type);
        } else {
            JOptionPane.showMessageDialog(this, "Maaf, metode tersebut tidak dapat dikonfigurasi");
        }
    }//GEN-LAST:event_buttonEditParameterMouseClicked

    private void buttonMulaiPelatihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMulaiPelatihanMouseClicked
        if(this.textNamaPelatihan.getText().isEmpty() || this.comboDataset.getSelectedObjects().length < 1) 
            JOptionPane.showMessageDialog(this, "Maaf, nama pelatihan harus diisi");
        else this.controller.responseMulaiPelatihan();
    }//GEN-LAST:event_buttonMulaiPelatihanMouseClicked

    private void comboMetodeEkstraksiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboMetodeEkstraksiItemStateChanged
        this.controller.setConfigExtractionToDefault(this.comboMetodeEkstraksi.getSelectedIndex());
    }//GEN-LAST:event_comboMetodeEkstraksiItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPelatihan().setVisible(true);
            }
        });
    }

    public JButton getButtonEditParameter() {
        return buttonEditParameter;
    }

    public JButton getButtonMulaiPelatihan() {
        return buttonMulaiPelatihan;
    }

    public JComboBox<String> getComboDataset() {
        return comboDataset;
    }

    public JComboBox<String> getComboMetodeEkstraksi() {
        return comboMetodeEkstraksi;
    }

    public JProgressBar getProgressPelatihan() {
        return progressPelatihan;
    }

    public JSpinner getSpinnerJumlahTree() {
        return spinnerJumlahTree;
    }

    public JTextField getTextNamaPelatihan() {
        return textNamaPelatihan;
    }

    public JComboBox<String> getComboCountAttributesCheckType() {
        return comboCountAttributesCheckType;
    }

    public JLabel getLabelInfoProgress() {
        return labelInfoProgress;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditParameter;
    private javax.swing.JButton buttonMulaiPelatihan;
    private javax.swing.JComboBox<String> comboCountAttributesCheckType;
    private javax.swing.JComboBox<String> comboDataset;
    private javax.swing.JComboBox<String> comboMetodeEkstraksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelInfoProgress;
    private javax.swing.JProgressBar progressPelatihan;
    private javax.swing.JSpinner spinnerJumlahTree;
    private javax.swing.JTextField textNamaPelatihan;
    // End of variables declaration//GEN-END:variables
}
