/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerHome;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author acdwisu
 */
public class MenuHome extends javax.swing.JFrame {
    
    
    ControllerHome controller;
    
    /**
     * Creates new form MenuHome
     */
    public MenuHome() {
        initComponents();
        
        // <editor-fold defaultstate="collapsed" desc="Look and Feel">
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MenuHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        // </editor-fold>
        
        // inisialisasi atribut-atribut member
        controller = new ControllerHome();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelBanner = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonDataLatih = new javax.swing.JButton();
        buttonDataUji = new javax.swing.JButton();
        buttonPelatihan = new javax.swing.JButton();
        buttonSegmentasi = new javax.swing.JButton();
        buttonKomparasi = new javax.swing.JButton();
        buttonHasil = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arabic Word Segmenter");
        setBackground(new java.awt.Color(102, 102, 102));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        labelBanner.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelBanner.setText("Arabic Word Segmenter");
        jPanel1.add(labelBanner, new java.awt.GridBagConstraints());

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEtchedBorder()));

        buttonDataLatih.setText("Data Latih");
        buttonDataLatih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDataLatihMouseClicked(evt);
            }
        });

        buttonDataUji.setText("Data Uji");
        buttonDataUji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDataUjiMouseClicked(evt);
            }
        });

        buttonPelatihan.setText("Pelatihan");
        buttonPelatihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPelatihanMouseClicked(evt);
            }
        });

        buttonSegmentasi.setText("Segmentasi");
        buttonSegmentasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSegmentasiMouseClicked(evt);
            }
        });

        buttonKomparasi.setText("Komparasi");
        buttonKomparasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonKomparasiMouseClicked(evt);
            }
        });

        buttonHasil.setText("Hasil");
        buttonHasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHasilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSegmentasi)
                    .addComponent(buttonPelatihan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDataUji, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonKomparasi, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addComponent(buttonDataLatih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonHasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonDataLatih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonDataUji)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPelatihan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSegmentasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonKomparasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonHasil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method untuk menghandle apabila <code> buttonDataLatih </code> di-clik
     * @param evt Event yang terjadi, yakni onMouseClicked
     */
    private void buttonDataLatihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDataLatihMouseClicked
        this.controller.openMenu(ControllerHome.MENU_DATA_LATIH);
    }//GEN-LAST:event_buttonDataLatihMouseClicked

    /**
     * Method untuk menghandle apabila <code> buttonDataUji </code> di-clik
     * @param evt Event yang terjadi, yakni onMouseClicked
     */
    private void buttonDataUjiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDataUjiMouseClicked
        this.controller.openMenu(ControllerHome.MENU_DATA_UJI);
    }//GEN-LAST:event_buttonDataUjiMouseClicked

    /**
     * Method untuk menghandle apabila <code> buttonPelatihan </code> di-clik
     * @param evt Event yang terjadi, yakni onMouseClicked
     */
    private void buttonPelatihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPelatihanMouseClicked
        this.controller.openMenu(ControllerHome.MENU_PELATIHAN);
    }//GEN-LAST:event_buttonPelatihanMouseClicked

    /**
     * Method untuk menghandle apabila <code> buttonSegmentasi </code> di-clik
     * @param evt Event yang terjadi, yakni onMouseClicked
     */
    private void buttonSegmentasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSegmentasiMouseClicked
        this.controller.openMenu(ControllerHome.MENU_SEGMENTASI);
    }//GEN-LAST:event_buttonSegmentasiMouseClicked

    /**
     * Method untuk menghandle apabila <code> buttonKomparasi </code> di-clik
     * @param evt Event yang terjadi, yakni onMouseClicked
     */
    private void buttonKomparasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKomparasiMouseClicked
        this.controller.openMenu(ControllerHome.MENU_KOMPARASI);
    }//GEN-LAST:event_buttonKomparasiMouseClicked

    /**
     * Method untuk menghandle apabila <code> buttonHasil </code> di-clik
     * @param evt Event yang terjadi, yakni onMouseClicked
     */
    private void buttonHasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHasilMouseClicked
        this.controller.openMenu(ControllerHome.MENU_HASIL);
    }//GEN-LAST:event_buttonHasilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDataLatih;
    private javax.swing.JButton buttonDataUji;
    private javax.swing.JButton buttonHasil;
    private javax.swing.JButton buttonKomparasi;
    private javax.swing.JButton buttonPelatihan;
    private javax.swing.JButton buttonSegmentasi;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelBanner;
    // End of variables declaration//GEN-END:variables
}
